name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-php-83:
    runs-on: ubuntu-latest

    container:
      image: cylab/php:8.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --memory-limit=1G

      - name: Run PHPCS
        run: ./vendor/bin/phpcs

      # we need elasticsearch to run phpunit tests
      # => to be fixed!
      #- name: Run PHPUnit
      #  run: ./vendor/bin/phpunit

